theme: jekyll-theme-minimal
title: Elle Buser
description: ebuser [at] emory [dot] edu 
<img src='https://raw.githubusercontent.com/ellebuser/ellebuser.github.io/main/documents/Buser.png' width='25'>
#logo: /documents/Buser.png
#https://raw.githubusercontent.com/ellebuser/ellebuser.github.io/main/documents/Buser.png
