theme: jekyll-theme-minimal
title: "Elle Buser"
description: <a href=mailto:"ebuser@emory.edu">Testing Landing Page</a>
logo: https://raw.githubusercontent.com/ellebuser/ellebuser.github.io/main/documents/Buser.png


