theme: jekyll-theme-minimal
title: Elle Buser
description: ebuser [at] emory [dot] edu 

include:
  - assets/css/styles.css

logo: https://raw.githubusercontent.com/ellebuser/ellebuser.github.io/main/documents/Buser.png
#picture: <img src="https://raw.githubusercontent.com/ellebuser/ellebuser.github.io/main/documents/Buser.png" class="custom-image">

