theme: jekyll-theme-minimal
title: "Elle Buser"
description: Email: <a href=mailto:"ebuser@emory.edu">ebuser@emory.edu</a>
logo: https://raw.githubusercontent.com/ellebuser/ellebuser.github.io/main/documents/Buser.png


