theme: jekyll-theme-minimal
title: Elle Buser
description: PhD Student at Emory University

<html>
  <head>
    <meta charset="utf-8">
    <title>{{ page.title }}</title>
  </head>
  <body>
    {% include navigation.html %}
    {{ content }}
  </body>
</html>
